name: Publish NuGet package

on:
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: | 
          8.0.x
          10.0.x

    - name: Restore solution
      shell: pwsh
      run: dotnet restore --nologo --verbosity quiet
      
    - name: Build solution
      shell: pwsh
      run: dotnet build --no-restore --configuration Release --nologo --verbosity quiet

    - name: Make package
      shell: pwsh
      run: dotnet pack ./AlexandreHtrb.WebSocketExtensions/AlexandreHtrb.WebSocketExtensions.csproj --nologo --verbosity quiet --configuration Release 
      
    - name: Read package version
      shell: pwsh
      run: |
        ([XML]$nugetCsprojXml = Get-Content ./AlexandreHtrb.WebSocketExtensions/AlexandreHtrb.WebSocketExtensions.csproj)
        $versionName = $nugetCsprojXml.Project.PropertyGroup.PackageVersion
        echo "VERSION_NAME=${versionName}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - name: Push package to NuGet
      shell: pwsh
      run: |
        $filePath = "./AlexandreHtrb.WebSocketExtensions/bin/Release/AlexandreHtrb.WebSocketExtensions.${env:VERSION_NAME}.nupkg"
        dotnet nuget push $filePath --api-key $env:NUGET_API_KEY --source https://api.nuget.org/v3/index.json
        if ($LastExitCode -ne 0)
        {
          exit 1;
        }
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        # para produção: NUGET_API_KEY, https://api.nuget.org/v3/index.json
        # para testes: QA_NUGET_API_KEY, https://apiint.nugettest.org/v3/index.json
